---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: redis-data-redis-cluster-master-1
spec: 
  accessModes: 
    - ReadWriteOnce
  claimRef:
    name: redis-data-redis-cluster-master-1 
    namespace: default        
  awsElasticBlockStore: 
    fsType: ext4
    volumeID: vol-04e7d33180f51e8af
  capacity: 
    storage: 100Gi
  storageClassName: ebs-disk
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - us-west-2a
        - key: topology.kubernetes.io/region
          operator: In
          values:
          - us-west-2  
---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: redis-data-redis-cluster-replicas-3
spec: 
  accessModes: 
    - ReadWriteOnce
  claimRef:
    name: redis-data-redis-cluster-replicas-3 
    namespace: default        
  awsElasticBlockStore: 
    fsType: ext4
    volumeID: vol-006f2e6795f79bfdf
  capacity: 
    storage: 100Gi
  storageClassName: ebs-disk 
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - us-west-2a
        - key: topology.kubernetes.io/region
          operator: In
          values:
          - us-west-2   
---
 kind: PersistentVolumeClaim
 apiVersion: v1
 metadata:
   name: redis-data-redis-cluster-master-1
 spec:
   storageClassName: gp2
   volumeMode: Filesystem
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 8Gi
---
 kind: PersistentVolumeClaim
 apiVersion: v1
 metadata:
   name: redis-data-redis-cluster-replicas-3
 spec:
   storageClassName: gp2
   volumeMode: Filesystem
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 8Gi
