---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: demo-1
spec: 
  accessModes: 
    - ReadWriteOnce
  claimRef:
    name: demo-1 
    namespace: default        
  awsElasticBlockStore: 
    fsType: ext4
    volumeID: vol-04e7d33180f51e8af
  capacity: 
    storage: 100Gi
  storageClassName: ebs-disk
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - us-west-2a
        - key: topology.kubernetes.io/region
          operator: In
          values:
          - us-west-2  
---
 kind: PersistentVolumeClaim
 apiVersion: v1
 metadata:
   name: demo-1
 spec:
   storageClassName: gp2
   volumeMode: Filesystem
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 8Gi
